1. Gunakan semua file yang ada di link di bawah. Data Penumpang Bus Sekolah 2017-2019.
Link:
  1. https://data.jakarta.go.id/dataset/data-penumpang-bus-sekolah-kpi
  2. https://data.jakarta.go.id/dataset/data-penumpang-bus-sekolah-tahun-2018-kpi
  3. https://data.jakarta.go.id/dataset/data-penumpang-bus-sekolah-tahun-2019-kpi

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
link_penumpang_bus = {
    '2017': {
    'januari': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/e4b640be-d9a2-4ea0-b94f-b5313385c04c/download/Penumpang-Bus-Sekolah-Januari-2017.csv',
    'februari': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/37205a79-ddae-4ef1-a3ac-4df1fb343754/download/Penumpang-Bus-Sekolah-Februari-2017.csv',
    'maret': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/24f1c29f-539e-442a-9a63-c68fff3093da/download/Penumpang-Bus-Sekolah-Maret-2017.csv',
    'april': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/fb5b4760-2a36-47ef-b037-e99c23fd9461/download/Penumpang-Bus-Sekolah-April-2017.csv',
    'mei': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/f9236311-cdec-438d-9127-bf426a0b0b42/download/Penumpang-Bus-Sekolah-Mei-2017.csv',
    'juni': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/724e0d36-a683-40e2-aa5e-c4310e873b5d/download/Penumpang-Bus-Sekolah-Juni-2017.csv',
    'juli': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/6b325948-ddf6-4da1-a96f-268055859285/download/Penumpang-Bus-Sekolah-Juli-2017.csv',
    'agustus': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/04781028-0ffa-4ef7-9356-d52460e1f824/download/Penumpang-Bus-Sekolah-Agustus-2017.csv',
    'september': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/18a8356c-5263-4119-be05-652c28b8ea67/download/Penumpang-Bus-Sekolah-September-2017.csv',
    'oktober': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/7eb98893-67c6-403d-83cd-951d6dacf197/download/Penumpang-Bus-Sekolah-Oktober-2017.csv',
    'november': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/2a9e76b7-b044-4384-a329-5bc681bf8cf7/download/Penumpang-Bus-Sekolah-November-2017.csv',
    'desember': 'https://data.jakarta.go.id/dataset/7cf2294c-b2d8-4960-9473-45b973ab4273/resource/29c3eced-52c0-408d-8b65-b6047ad29b22/download/Penumpang-Bus-Sekolah-Desember-2017.csv'
    },
    '2018': {
        'januari': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/66adb89a-ae5d-462a-b0b4-3029ae108693/download/Data-Penumpang-Bus-Sekolah-Januari-2018.csv',
        'februari': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/f1ad67c2-1a66-4d48-bec4-03d67b3595b4/download/Data-Penumpang-Bus-Sekolah-Februari-2018.csv',
        'maret': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/9db1c6a8-ba55-4099-b325-6f9708dd93be/download/Data-Penumpang-Bus-Sekolah-Maret-2018.csv',
        'april': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/cfe8b2a1-ca56-4f54-9719-2fdef07b3f58/download/Data-Penumpang-Bus-Sekolah-April-2018.csv',
        'mei': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/2f6cfb75-0b15-4c58-8259-8258ba744931/download/Data-Penumpang-Bus-Sekolah-Mei-2018.csv',
        'juni': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/f8b54e46-dd99-4303-9604-00221a05e95d/download/Data-Penumpang-Bus-Sekolah-Juni-2018.csv',
        'juli': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/64b338e7-f40b-4aab-a2d7-0dcd305e4ce8/download/Data-Penumpang-Bus-Sekolah-Juli-2018.csv',
        'agustus': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/935859ce-a92b-4b3a-99fb-f517f4a7b89d/download/Data-Penumpang-Bus-Sekolah-Agustus-2018.csv',
        'september': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/7a281451-6b3a-492f-881c-daab0440b338/download/Data-Penumpang-Bus-Sekolah-September-2018.csv',
        'oktober': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/1871014a-94bb-4693-ace0-230f629d089d/download/Data-Penumpang-Bus-Sekolah-Oktober-2018.csv',
        'november': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/55a21757-3313-44d6-bafe-0721b86b5f99/download/Data-Penumpang-Bus-Sekolah-November-2018.csv',
        'desember': 'https://data.jakarta.go.id/dataset/737d708e-0eea-4734-acdc-9038a38692ca/resource/12040d13-1079-4c4c-b1a8-73ce3f821d17/download/Data-Penumpang-Bus-Sekolah-Desember-2018.csv'
    },
    '2019': {
        'januari': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/f268abb0-a698-48c7-89c0-98e89db6fde5/download/Data-Penumpang-Bus-Sekolah-Januari-2019.csv',
        'februari': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/2db6ec67-2217-4da1-a994-7bf770502997/download/Data-Penumpang-Bus-Sekolah-Februari-2019.csv',
        'maret': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/2e15072d-c4dd-4334-9b73-bbe09cd05d38/download/Data-Penumpang-Bus-Sekolah-Maret-2019.csv',
        'april': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/cadde2eb-61af-4e66-ad99-2d96daea2730/download/Data-Penumpang-Bus-Sekolah-April-2019.csv',
        'mei': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/d0f8993e-e422-4241-adec-b638ec673087/download/Data-Penumpang-Bus-Sekolah-Mei-2019.csv',
        'juni': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/dfdd18da-f011-419c-ba11-4cac7011f086/download/Data-Penumpang-Bus-Sekolah-Juni-2019.csv',
        'juli': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/17a1f125-3cdd-43f9-ade5-59265a8a629b/download/Data-Penumpang-Bus-Sekolah-Juli-2019.csv',
        'agustus': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/8b581cad-7b58-4761-b1fa-aa677a4323ef/download/Data-Penumpang-Bus-Sekolah-Agustus-2019.csv',
        'september': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/a7cf979a-520b-40e1-a2dc-ef131f350379/download/Data-Penumpang-Bus-Sekolah-September-2019.csv',
        'oktober': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/42444774-1bea-4e56-b626-d843f73580ea/download/Data-Penumpang-Bus-Sekolah-Oktober-2019.csv',
        'november': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/ab104258-0574-4b62-b4cc-63843d8b843d/download/Data-Penumpang-Bus-Sekolah-November-2019.csv',
        'desember': 'https://data.jakarta.go.id/dataset/97ce3df4-c76c-41f5-a26f-6661fd760701/resource/6f307bfe-836d-4bd9-9f96-1f667925ab8c/download/Data-Penumpang-Bus-Sekolah-Desember-2019.csv'
    }
}

2. Gabungkan semua dataset menjadi satu.

3. Tambahkan column ‘tahun’ dan ‘bulan’ sesuai dengan keterangan tanggal pada website

In [3]:
df_penumpang_bus_all = pd.DataFrame()

for tahun, semua_bulan in link_penumpang_bus.items():
  for bulan, link in semua_bulan.items():
    try:
      df_penumpang_bus_per_bulan = pd.read_csv(link)
    except UnicodeDecodeError:
      df_penumpang_bus_per_bulan = pd.read_csv(link, encoding='latin1')

    df_penumpang_bus_per_bulan['bulan'] = str(bulan) #menambahkan kolom bulan
    df_penumpang_bus_per_bulan['tahun'] = int(tahun) #menambahkan kolom tahun
    df_penumpang_bus_all = df_penumpang_bus_all.append(df_penumpang_bus_per_bulan).reset_index(drop=True) #memasukkan data per bulan ke dataframe keseluruhan

df_penumpang_bus_all

<ipython-input-3-23882e11cef8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_penumpang_bus_all = df_penumpang_bus_all.append(df_penumpang_bus_per_bulan).reset_index(drop=True) #memasukkan data per bulan ke dataframe keseluruhan
<ipython-input-3-23882e11cef8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_penumpang_bus_all = df_penumpang_bus_all.append(df_penumpang_bus_per_bulan).reset_index(drop=True) #memasukkan data per bulan ke dataframe keseluruhan
<ipython-input-3-23882e11cef8>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_penumpang_bus_all = df_penumpang_bus_all.append(df_penumpang_bus_per_bulan).reset_index(drop=True) #memasukkan data per bulan ke dataframe keseluruhan
<ipython-input-3-23882e11cef

type_operasi                               daerah_operasi  \
0          ZONASI                                       ZONA 1   
1          ZONASI                                       ZONA 2   
2          ZONASI                                       ZONA 3   
3          ZONASI                                       ZONA 4   
4          ZONASI                                       ZONA 5   
...           ...                                          ...   
1155       ZONASI                                    ZONASI 10   
1156       ZONASI                                    ZONASI 11   
1157       ZONASI                                    ZONASI 12   
1158       ZONASI  ZONASI UJI COBA (CIPEDAK – SRENGSENG SAWAH)   
1159       ZONASI                          ZONASI RENOP KHUSUS   

                                           area_operasi  jumlah_bus  \
0           ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO       100.0   
1                         ZONASI KP.MELAYU - RAWAMANGUN        84.0   
2                     ZONASI TERMINAL KALIDERES - KAMAL        67.0   
3                 ZONASI KALIDERES -SEMANAN-DURIKOSAMBI       102.0   
4                    ZONASI PULO GADUNG-MARDANI-PASEBAN        68.0   
...                                                 ...         ...   
1155                   ZONASI 10 (RUSUNAWA - CILINCING)        35.0   
1156  ZONASI 11 (RUSUN KAPUK MUARA - JEMBATAN LIMA -...        27.0   
1157  ZONASI 12 (RUSUN RAWABEBEK - CAKUNG TIMUR - RO...        28.0   
1158        ZONASI UJI COBA (CIPEDAK – SRENGSENG SAWAH)        53.0   
1159                                ZONASI RENOP KHUSUS        68.0   

     jumlah_penumpang     bulan  tahun  Unnamed: 5  ritase  
0             20358.0   januari   2017         NaN     NaN  
1             16302.0   januari   2017         NaN     NaN  
2             11416.0   januari   2017         NaN     NaN  
3             18655.0   januari   2017         NaN     NaN  
4             12332.0   januari   2017         NaN     NaN  
...               ...       ...    ...         ...     ...  
1155            6,810  desember   2019         NaN     NaN  
1156            3,509  desember   2019         NaN     NaN  
1157            4,533  desember   2019         NaN     NaN  
1158            6,799  desember   2019         NaN     NaN  
1159            7,758  desember   2019         NaN     NaN  

[1160 rows x 9 columns]

In [4]:
#untuk menampilkan informasi statistik untuk setiap kolom
df_penumpang_bus_all.describe()

jumlah_bus        tahun  Unnamed: 5       ritase
count  1156.000000  1160.000000         0.0    29.000000
mean     75.742215  2018.046552         NaN  1901.586207
std      44.249188     0.825336         NaN  1238.208773
min       0.000000  2017.000000         NaN    21.000000
25%      50.000000  2017.000000         NaN  1066.000000
50%      70.000000  2018.000000         NaN  1868.000000
75%      94.000000  2019.000000         NaN  2477.000000
max     771.000000  2019.000000         NaN  4669.000000

In [5]:
#untuk menampilkan jumlah record
df_penumpang_bus_all.shape

(1160, 9)

In [6]:
#melihat isi kolom 'Unnamed: 5'
df_penumpang_bus_all['Unnamed: 5'].unique()

array([nan])

In [7]:
#drop kolom 'Unnamed :5' karena hanya berisi NaN
df_penumpang_bus_all = df_penumpang_bus_all.drop('Unnamed: 5', axis=1)

In [8]:
#melihat isi kolom 'ritase'
df_penumpang_bus_all['ritase'].unique()

array([  nan, 2925., 2179., 1118., 1868., 1372.,  953., 1168., 1123.,
       1147., 1008.,  702., 4163., 2712., 3333., 2239., 3351.,  436.,
       2257., 4669., 2477., 1066.,   21., 4302.,  251., 2198., 2107.,
        197., 1936.])

In [9]:
#drop kolom 'ritase' karena hanya ada pada data satu bulan
df_penumpang_bus_all = df_penumpang_bus_all.drop('ritase', axis=1)

4. Lakukan data manipulation pada jumlah_bus dan jumlah_penumpang supaya berada dalam satu format type. Contoh:
  1. 89.96 => 8996
  2. 9000.0 => 9000
  3. 9000,0 => 9000

In [10]:
#untuk menampilkan tipe data dari setiap kolom
df_penumpang_bus_all.dtypes

type_operasi         object
daerah_operasi       object
area_operasi         object
jumlah_bus          float64
jumlah_penumpang     object
bulan                object
tahun                 int64
dtype: object

karena jumlah_penumpang masi berupa string, ubah ke int

In [11]:
df_penumpang_bus_all.head()

type_operasi daerah_operasi                                 area_operasi  \
0       ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
1       ZONASI         ZONA 2                ZONASI KP.MELAYU - RAWAMANGUN   
2       ZONASI         ZONA 3            ZONASI TERMINAL KALIDERES - KAMAL   
3       ZONASI         ZONA 4        ZONASI KALIDERES -SEMANAN-DURIKOSAMBI   
4       ZONASI         ZONA 5           ZONASI PULO GADUNG-MARDANI-PASEBAN   

   jumlah_bus jumlah_penumpang    bulan  tahun  
0       100.0          20358.0  januari   2017  
1        84.0          16302.0  januari   2017  
2        67.0          11416.0  januari   2017  
3       102.0          18655.0  januari   2017  
4        68.0          12332.0  januari   2017

In [12]:
df_penumpang_bus_all.dtypes

type_operasi         object
daerah_operasi       object
area_operasi         object
jumlah_bus          float64
jumlah_penumpang     object
bulan                object
tahun                 int64
dtype: object

In [13]:
#untuk menampilkan nilai unik dari suatu kolom
df_penumpang_bus_all['jumlah_penumpang'].unique()

array([20358.0, 16302.0, 11416.0, ..., '4,533', '6,799', '7,758'],
      dtype=object)

In [14]:
#Function untuk mengubah tipe data menjadi integer
def ChangeType(x):
  if isinstance(x,str):
    a = x.replace(',','')
    b = float(a)
    c = int(b)
  else:
    c = int(x)
  return c

In [15]:
df_penumpang_bus_all['jumlah_penumpang'] = df_penumpang_bus_all['jumlah_penumpang'].fillna(0) #mengisi nilai NaN dengan 0
df_penumpang_bus_all['jumlah_penumpang'] = df_penumpang_bus_all['jumlah_penumpang'].apply(ChangeType) #mengganti tipe data menjadi integer

In [16]:
df_penumpang_bus_all.head()

type_operasi daerah_operasi                                 area_operasi  \
0       ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
1       ZONASI         ZONA 2                ZONASI KP.MELAYU - RAWAMANGUN   
2       ZONASI         ZONA 3            ZONASI TERMINAL KALIDERES - KAMAL   
3       ZONASI         ZONA 4        ZONASI KALIDERES -SEMANAN-DURIKOSAMBI   
4       ZONASI         ZONA 5           ZONASI PULO GADUNG-MARDANI-PASEBAN   

   jumlah_bus  jumlah_penumpang    bulan  tahun  
0       100.0             20358  januari   2017  
1        84.0             16302  januari   2017  
2        67.0             11416  januari   2017  
3       102.0             18655  januari   2017  
4        68.0             12332  januari   2017

In [17]:
#melihat isi kolom 'jumlah_bus'
df_penumpang_bus_all['jumlah_bus'].unique()

array([100.,  84.,  67., 102.,  68.,  66.,  50.,  51.,  34.,  94.,  80.,
        95.,  63.,  79., 128., 101.,  82.,  49.,  85., 109.,  93.,  74.,
       113.,  75.,  76.,  56.,  57.,  37., 114., 112., 152.,  91.,  83.,
        73.,  38.,  36., 127., 107.,  86.,  87.,  65.,  42., 131.,  88.,
       175., 103., 110., 108.,  39.,  45.,  44.,  99.,  70.,  33., 137.,
        77.,  97., 122.,  89.,  55.,  41.,  47.,  21.,  60.,  69.,  53.,
        22.,  35.,  28.,  54.,  27.,  18.,  29.,  72.,  52.,  40.,  43.,
        26.,  20.,  58.,  31.,  30.,  24.,  15.,   2.,  62.,  64.,  48.,
       124.,  92.,  32., 105., 111., 104., 146.,  nan, 121.,  10.,   8.,
        59.,  46., 126.,  98., 123., 129., 132., 174., 119., 117., 125.,
        71., 106.,  90.,  81.,  78.,  25.,  19.,  14.,  12.,  13.,  11.,
        61., 144., 116., 143., 180.,   0., 164., 153., 167., 162., 120.,
       133., 183., 150., 115., 195., 154., 179., 147., 141., 198., 135.,
       283., 136.,  96., 130., 118., 270., 134.,  2

In [18]:
df_penumpang_bus_all['jumlah_bus'] = df_penumpang_bus_all['jumlah_bus'].fillna(0) #mengisi nilai NaN dengan 0
df_penumpang_bus_all['jumlah_bus'] = df_penumpang_bus_all['jumlah_bus'].apply(ChangeType) #mengganti tipe data menjadi integer

In [19]:
df_penumpang_bus_all.head()

type_operasi daerah_operasi                                 area_operasi  \
0       ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
1       ZONASI         ZONA 2                ZONASI KP.MELAYU - RAWAMANGUN   
2       ZONASI         ZONA 3            ZONASI TERMINAL KALIDERES - KAMAL   
3       ZONASI         ZONA 4        ZONASI KALIDERES -SEMANAN-DURIKOSAMBI   
4       ZONASI         ZONA 5           ZONASI PULO GADUNG-MARDANI-PASEBAN   

   jumlah_bus  jumlah_penumpang    bulan  tahun  
0         100             20358  januari   2017  
1          84             16302  januari   2017  
2          67             11416  januari   2017  
3         102             18655  januari   2017  
4          68             12332  januari   2017

In [20]:
df_penumpang_bus_all.dtypes

type_operasi        object
daerah_operasi      object
area_operasi        object
jumlah_bus           int64
jumlah_penumpang     int64
bulan               object
tahun                int64
dtype: object

5. Lakukan aggregasi sum, mean, dan max dari jumlah_bus dan jumlah_penumpang berdasarkan tahun

In [21]:
df_hasil_agg = df_penumpang_bus_all.groupby('tahun').agg(
    sum_jumlah_bus = ('jumlah_bus','sum'),
    mean_jumlah_bus = ('jumlah_bus','mean'),
    max_jumlah_bus = ('jumlah_bus','max'),
    sum_jumlah_penumpang = ('jumlah_penumpang','sum'),
    mean_jumlah_penumpang = ('jumlah_penumpang','mean'),
    max_jumlah_penumpang = ('jumlah_penumpang','max')
)

In [22]:
df_hasil_agg

sum_jumlah_bus  mean_jumlah_bus  max_jumlah_bus  sum_jumlah_penumpang  \
tahun                                                                          
2017            25067        67.932249             175               3972612   
2018            25369        68.937500             183                671366   
2019            37122        87.758865             771               3919525   

       mean_jumlah_penumpang  max_jumlah_penumpang  
tahun                                               
2017            10765.886179                 42338  
2018             1824.364130                 40336  
2019             9266.016548                 48833

6. Simpan hasil aggregasi dalam bentuk json file

In [23]:
df_hasil_agg.to_json('./test_result.json', orient='records')